### ISSUE TITLE
Distributed & matrix-free version

### ISSUE THREAD

**Issue by rleegates** [JuliaInv/Multigrid.jl#1]
Dear developers,

I just stumbled across your package, which I really like. However, I'm actually looking for a distributed version of algebraic multi-grid which uses a matrix-free residual computation. Do you have an idea as to how much work it would be to adapt the package to my use-case?

Best regards,
Robert

**Comment by erantreister** [comment]
Hi Robert,

The package currently does not support what you need. It is a sparse-matrix
based package which assumes that the linear system fits in the memory of
the machine. It will take some work to adapt it to what you need.

I do wonder - how can "Algebraic Multigrid" be matrix-free? Do you mean
geometric multigrid or black-box at least?

Cheers,
Eran.
